[CP4BA] Add custom database for BAW
IBM/cloud-pak-deployer pull request #826
Opened 2024-11-03 00:05 UTC by P-147

Hello cpd team! 

Today, I'm adding a small improvement for BAW (Business Automation Workflow) in the CP4BA 😄
This is something I had to configure manually multiple times for client demos, and would like to automate in the future.

**TL;DR:**
This patch add the creation of a new database `bawsql` on the Postgres instance, and register it on the Liberty server running BAW (Authoring).  
This allow workflow designers to reference this new db from BAW, and perform SQL operations using the 'System Data' Toolkit.

**List of Changes:**
- Add ansible create / delete tasks for `bawsql` database
- Add example table `user_db` with sample data in the `bawsql` db
- Renamed Secret template `bawaut-custom-xml-secret.yaml.j2` ‎to `bawaut-lombardi-custom-xml-secret.yaml.j2` for clarity
- Add Secret template `bawaut-liberty-custom-xml-secret.yaml.j2` with `bawsql` connection informations and register it on the CP4BA operator instance
- Add documentation in `cp4ba-usage` on how to use the `bawsql` db connection in BAW

Let me know if I need to change something :)

2024-11-11 07:21 UTC, jandusek4 requested changes
Custom100.xml to 100Custom.xml

2024-11-11 07:21 UTC, jandusek4 commented on automation-roles/50-install-cloud-pak/cp4ba/cp4ba-core/tasks/predeploy/bawaut.yml
> +- name: Prepare yaml file for BAWAUT Lombardi Custom100.xml Secret
Custom100.xml to 100Custom.xml

2024-11-11 07:21 UTC, jandusek4 commented on automation-roles/50-install-cloud-pak/cp4ba/cp4ba-core/tasks/predeploy/bawaut.yml
> +- name: Add BAWAUT Lombardi Custom100.xml Secret
Custom100.xml to 100Custom.xml

2024-11-11 18:30 UTC, P-147 commented on automation-roles/50-install-cloud-pak/cp4ba/cp4ba-core/tasks/predeploy/bawaut.yml
> +- name: Prepare yaml file for BAWAUT Lombardi Custom100.xml Secret
Fixed in next commit  (391bb97)

2024-11-11 18:30 UTC, P-147 commented on automation-roles/50-install-cloud-pak/cp4ba/cp4ba-core/tasks/predeploy/bawaut.yml
> +- name: Add BAWAUT Lombardi Custom100.xml Secret
Fixed in next commit  (391bb97)

2024-11-12 06:15 UTC, jandusek4 approved these changes
Now its all good!

2024-11-12 06:17 UTC, merged